name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
        
      - name: Build vite app
        run: npm run build:vite
          
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: "ec2-54-169-52-222.ap-southeast-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/axonstech"

      - name: Post Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-54-169-52-222.ap-southeast-1.compute.amazonaws.com"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd axonstech
            pwd
            #pm2 restart "npm run dev"
